# Generated by Django 3.2.3 on 2021-06-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_n_shop_codefiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.TextField(default=None, max_length=150),
        ),
    ]
