# Generated by Django 3.2.3 on 2021-06-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_n_shop_codefiles', '0002_auto_20210616_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pprice',
            field=models.IntegerField(),
        ),
    ]
