# Generated by Django 3.2.3 on 2021-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_n_shop_codefiles', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='list',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
